-- Run this in Supabase SQL Editor

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  email text not null unique,
  role text not null check (role in ('student', 'counselor', 'teacher', 'parent')),
  school_id text not null,
  school_name text not null default '',
  grade_level text,
  title text,
  department text,
  profile_image text,
  approved boolean not null default false,
  subject text,
  children_names text[],
  relationship text,
  created_at timestamptz not null default now()
);

create table if not exists public.requests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  status text not null default 'pending',
  category text not null,
  counselor_name text not null default 'Unassigned',
  counselor_id uuid references public.profiles(id) on delete set null,
  student_name text not null,
  student_id uuid not null references public.profiles(id) on delete cascade,
  school_id text not null,
  response text,
  documents jsonb default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  counselor_name text not null,
  counselor_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  school_id text not null,
  date text not null,
  time text not null,
  type text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_key text not null,
  sender_role text not null,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.message_reads (
  id bigint generated by default as identity primary key,
  conversation_key text not null,
  reader_id uuid not null references public.profiles(id) on delete cascade,
  last_read_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (conversation_key, reader_id)
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  school_id text not null,
  title text not null,
  progress integer not null default 0,
  deadline text not null,
  priority text not null default 'medium',
  created_at timestamptz not null default now()
);

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  counselor_id uuid not null references public.profiles(id) on delete cascade,
  school_id text not null,
  title text not null,
  description text not null,
  category text not null,
  type text not null,
  content text not null,
  status text not null default 'draft',
  created_at timestamptz not null default now()
);

create index if not exists idx_profiles_school_role on public.profiles (school_id, role);
create index if not exists idx_requests_school_student on public.requests (school_id, student_id);
create index if not exists idx_requests_school_counselor on public.requests (school_id, counselor_id);
create index if not exists idx_meetings_school_student on public.meetings (school_id, student_id);
create index if not exists idx_meetings_school_counselor on public.meetings (school_id, counselor_id);
create index if not exists idx_messages_conversation_created on public.messages (conversation_key, created_at desc);
create index if not exists idx_message_reads_reader_conversation on public.message_reads (reader_id, conversation_key);
create index if not exists idx_goals_school_student on public.goals (school_id, student_id);
create index if not exists idx_resources_school_status on public.resources (school_id, status);

create or replace function public.current_user_school_id()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.school_id
  from public.profiles p
  where p.id = auth.uid()
  limit 1;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.profiles p
  where p.id = auth.uid()
  limit 1;
$$;

grant execute on function public.current_user_school_id() to authenticated;
grant execute on function public.current_user_role() to authenticated;

alter table public.profiles enable row level security;
alter table public.requests enable row level security;
alter table public.meetings enable row level security;
alter table public.messages enable row level security;
alter table public.message_reads enable row level security;
alter table public.goals enable row level security;
alter table public.resources enable row level security;

-- Profiles policies
drop policy if exists profiles_select_same_school on public.profiles;
create policy profiles_select_same_school
on public.profiles
for select
to authenticated
using (
  id = auth.uid() or school_id = public.current_user_school_id()
);

drop policy if exists profiles_insert_self on public.profiles;
create policy profiles_insert_self
on public.profiles
for insert
to authenticated
with check (
  id = auth.uid()
);

drop policy if exists profiles_update_self_or_counselor on public.profiles;
create policy profiles_update_self_or_counselor
on public.profiles
for update
to authenticated
using (
  id = auth.uid()
  or (
    public.current_user_role() = 'counselor'
    and school_id = public.current_user_school_id()
  )
)
with check (
  id = auth.uid()
  or (
    public.current_user_role() = 'counselor'
    and school_id = public.current_user_school_id()
  )
);

drop policy if exists profiles_delete_counselor_school on public.profiles;
create policy profiles_delete_counselor_school
on public.profiles
for delete
to authenticated
using (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
);

-- Requests policies
drop policy if exists requests_select_school on public.requests;
create policy requests_select_school
on public.requests
for select
to authenticated
using (
  school_id = public.current_user_school_id()
);

drop policy if exists requests_insert_scope on public.requests;
create policy requests_insert_scope
on public.requests
for insert
to authenticated
with check (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
  )
);

drop policy if exists requests_update_scope on public.requests;
create policy requests_update_scope
on public.requests
for update
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
  )
)
with check (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
  )
);

drop policy if exists requests_delete_scope on public.requests;
create policy requests_delete_scope
on public.requests
for delete
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
  )
);

-- Meetings policies
drop policy if exists meetings_select_school on public.meetings;
create policy meetings_select_school
on public.meetings
for select
to authenticated
using (
  school_id = public.current_user_school_id()
);

drop policy if exists meetings_insert_scope on public.meetings;
create policy meetings_insert_scope
on public.meetings
for insert
to authenticated
with check (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
  )
);

drop policy if exists meetings_update_scope on public.meetings;
create policy meetings_update_scope
on public.meetings
for update
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    student_id = auth.uid()
    or public.current_user_role() = 'counselor'
  )
)
with check (
  school_id = public.current_user_school_id()
  and (
    student_id = auth.uid()
    or public.current_user_role() = 'counselor'
  )
);

drop policy if exists meetings_delete_scope on public.meetings;
create policy meetings_delete_scope
on public.meetings
for delete
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    student_id = auth.uid()
    or public.current_user_role() = 'counselor'
  )
);

-- Messages policies
drop policy if exists messages_select_school on public.messages;
create policy messages_select_school
on public.messages
for select
to authenticated
using (
  public.current_user_school_id() = (
    select p.school_id
    from public.profiles p
    where p.id = sender_id
    limit 1
  )
);

drop policy if exists messages_insert_self on public.messages;
create policy messages_insert_self
on public.messages
for insert
to authenticated
with check (
  sender_id = auth.uid()
  and public.current_user_school_id() = (
    select p.school_id
    from public.profiles p
    where p.id = sender_id
    limit 1
  )
);

drop policy if exists messages_update_sender on public.messages;
create policy messages_update_sender
on public.messages
for update
to authenticated
using (
  sender_id = auth.uid()
)
with check (
  sender_id = auth.uid()
);

drop policy if exists messages_delete_sender on public.messages;
create policy messages_delete_sender
on public.messages
for delete
to authenticated
using (
  sender_id = auth.uid()
);

-- Message reads policies
drop policy if exists message_reads_select_self on public.message_reads;
create policy message_reads_select_self
on public.message_reads
for select
to authenticated
using (
  reader_id = auth.uid()
);

drop policy if exists message_reads_insert_self on public.message_reads;
create policy message_reads_insert_self
on public.message_reads
for insert
to authenticated
with check (
  reader_id = auth.uid()
);

drop policy if exists message_reads_update_self on public.message_reads;
create policy message_reads_update_self
on public.message_reads
for update
to authenticated
using (
  reader_id = auth.uid()
)
with check (
  reader_id = auth.uid()
);

drop policy if exists message_reads_delete_self on public.message_reads;
create policy message_reads_delete_self
on public.message_reads
for delete
to authenticated
using (
  reader_id = auth.uid()
);

-- Goals policies
drop policy if exists goals_select_school on public.goals;
create policy goals_select_school
on public.goals
for select
to authenticated
using (
  school_id = public.current_user_school_id()
);

drop policy if exists goals_insert_scope on public.goals;
create policy goals_insert_scope
on public.goals
for insert
to authenticated
with check (
  school_id = public.current_user_school_id()
  and (
    student_id = auth.uid()
    or public.current_user_role() = 'counselor'
  )
);

drop policy if exists goals_update_scope on public.goals;
create policy goals_update_scope
on public.goals
for update
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    student_id = auth.uid()
    or public.current_user_role() = 'counselor'
  )
)
with check (
  school_id = public.current_user_school_id()
  and (
    student_id = auth.uid()
    or public.current_user_role() = 'counselor'
  )
);

drop policy if exists goals_delete_scope on public.goals;
create policy goals_delete_scope
on public.goals
for delete
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    student_id = auth.uid()
    or public.current_user_role() = 'counselor'
  )
);

-- Resources policies
drop policy if exists resources_select_school on public.resources;
create policy resources_select_school
on public.resources
for select
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    status = 'published'
    or public.current_user_role() = 'counselor'
  )
);

drop policy if exists resources_insert_counselor on public.resources;
create policy resources_insert_counselor
on public.resources
for insert
to authenticated
with check (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
  and counselor_id = auth.uid()
);

drop policy if exists resources_update_counselor on public.resources;
create policy resources_update_counselor
on public.resources
for update
to authenticated
using (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
)
with check (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
);

drop policy if exists resources_delete_counselor on public.resources;
create policy resources_delete_counselor
on public.resources
for delete
to authenticated
using (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
);
