-- Counselor-authored surveys/questionnaires targeted at students, parents, and/or teachers.
-- Run this in Supabase SQL Editor (see CLAUDE.md — migrations are not auto-applied).

create table if not exists public.surveys (
  id bigint generated by default as identity primary key,
  counselor_id uuid not null references public.profiles(id) on delete cascade,
  school_id text not null,
  title text not null,
  description text not null default '',
  questions jsonb not null default '[]'::jsonb,
  target_roles text[] not null default '{}'::text[],
  target_grades text[],
  anonymous boolean not null default false,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint surveys_status_check check (status in ('draft', 'published', 'closed')),
  constraint surveys_target_roles_check check (target_roles <@ array['student', 'parent', 'teacher']::text[])
);

-- Submitted answers. respondent_id is null when the parent survey is anonymous — content is
-- deliberately unlinked from identity in that case. Who has responded (regardless of anonymity)
-- is tracked separately in survey_receipts so the counselor can still chase non-responders.
create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  survey_id bigint not null references public.surveys(id) on delete cascade,
  respondent_id uuid references public.profiles(id) on delete cascade,
  respondent_role text not null,
  answers jsonb not null default '{}'::jsonb,
  submitted_at timestamptz not null default now()
);

create table if not exists public.survey_receipts (
  id bigint generated by default as identity primary key,
  survey_id bigint not null references public.surveys(id) on delete cascade,
  respondent_id uuid not null references public.profiles(id) on delete cascade,
  responded_at timestamptz not null default now()
);

create index if not exists idx_surveys_school_status on public.surveys (school_id, status);
create index if not exists idx_survey_responses_survey on public.survey_responses (survey_id);
create unique index if not exists idx_survey_responses_identified_unique
  on public.survey_responses (survey_id, respondent_id)
  where respondent_id is not null;
create index if not exists idx_survey_receipts_survey on public.survey_receipts (survey_id);
create unique index if not exists idx_survey_receipts_unique
  on public.survey_receipts (survey_id, respondent_id);

-- True only when the current user is an eligible recipient of the survey: same school, their
-- role is targeted, and — for students only — their grade is targeted (parents/teachers are
-- targeted by role alone; a parent's own grade_level is null so grade filtering doesn't apply).
create or replace function public.survey_targets_current_user(p_survey_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    s.school_id = public.current_user_school_id()
    and public.current_user_role() = any(s.target_roles)
    and (
      public.current_user_role() <> 'student'
      or s.target_grades is null
      or array_length(s.target_grades, 1) is null
      or exists (
        select 1 from public.profiles p
        where p.id = auth.uid() and p.grade_level = any(s.target_grades)
      )
    )
  from public.surveys s
  where s.id = p_survey_id;
$$;

grant execute on function public.survey_targets_current_user(bigint) to authenticated;

alter table public.surveys enable row level security;
alter table public.survey_responses enable row level security;
alter table public.survey_receipts enable row level security;

-- Surveys policies
drop policy if exists surveys_select on public.surveys;
create policy surveys_select
on public.surveys
for select
to authenticated
using (
  (public.current_user_role() = 'counselor' and school_id = public.current_user_school_id())
  or (status = 'published' and public.survey_targets_current_user(id))
);

drop policy if exists surveys_insert_counselor on public.surveys;
create policy surveys_insert_counselor
on public.surveys
for insert
to authenticated
with check (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
  and counselor_id = auth.uid()
);

drop policy if exists surveys_update_counselor on public.surveys;
create policy surveys_update_counselor
on public.surveys
for update
to authenticated
using (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
)
with check (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
);

drop policy if exists surveys_delete_counselor on public.surveys;
create policy surveys_delete_counselor
on public.surveys
for delete
to authenticated
using (
  public.current_user_role() = 'counselor'
  and school_id = public.current_user_school_id()
);

-- Survey responses policies
drop policy if exists survey_responses_select on public.survey_responses;
create policy survey_responses_select
on public.survey_responses
for select
to authenticated
using (
  (
    public.current_user_role() = 'counselor'
    and exists (
      select 1 from public.surveys s
      where s.id = survey_id and s.school_id = public.current_user_school_id()
    )
  )
  or respondent_id = auth.uid()
);

drop policy if exists survey_responses_insert_recipient on public.survey_responses;
create policy survey_responses_insert_recipient
on public.survey_responses
for insert
to authenticated
with check (
  public.survey_targets_current_user(survey_id)
  and respondent_role = public.current_user_role()
  and exists (
    select 1 from public.surveys s
    where s.id = survey_id
      and s.status = 'published'
      and (
        (s.anonymous = false and respondent_id = auth.uid())
        or (s.anonymous = true and respondent_id is null)
      )
  )
);

-- Survey receipts policies (completion tracking, kept separate from answer content)
drop policy if exists survey_receipts_select on public.survey_receipts;
create policy survey_receipts_select
on public.survey_receipts
for select
to authenticated
using (
  (
    public.current_user_role() = 'counselor'
    and exists (
      select 1 from public.surveys s
      where s.id = survey_id and s.school_id = public.current_user_school_id()
    )
  )
  or respondent_id = auth.uid()
);

drop policy if exists survey_receipts_insert_self on public.survey_receipts;
create policy survey_receipts_insert_self
on public.survey_receipts
for insert
to authenticated
with check (
  respondent_id = auth.uid()
  and public.survey_targets_current_user(survey_id)
  and exists (
    select 1 from public.surveys s where s.id = survey_id and s.status = 'published'
  )
);
