-- Career-guidance assessment results (Klimov DDO / grade 9, Holland RIASEC / grade 10,
-- Crites CMI / grade 11). One row per student per assessment type — a retake overwrites
-- the previous result rather than accumulating history, matching how the instrument is
-- meant to be used (a current snapshot for counseling, not a longitudinal record).
-- Run this in Supabase SQL Editor (see CLAUDE.md — migrations are not auto-applied).

create table if not exists public.career_assessment_results (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  school_id text not null,
  assessment_type text not null,
  grade_level text,
  answers jsonb not null default '{}'::jsonb,
  scores jsonb not null default '{}'::jsonb,
  headline text not null default '',
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint career_assessment_results_type_check check (assessment_type in ('ddo', 'riasec', 'cmi'))
);

create unique index if not exists idx_career_assessment_results_unique
  on public.career_assessment_results (student_id, assessment_type);
create index if not exists idx_career_assessment_results_school
  on public.career_assessment_results (school_id, assessment_type);

alter table public.career_assessment_results enable row level security;

drop policy if exists career_assessment_results_select on public.career_assessment_results;
create policy career_assessment_results_select
on public.career_assessment_results
for select
to authenticated
using (
  student_id = auth.uid()
  or (public.current_user_role() = 'counselor' and school_id = public.current_user_school_id())
);

drop policy if exists career_assessment_results_insert_self on public.career_assessment_results;
create policy career_assessment_results_insert_self
on public.career_assessment_results
for insert
to authenticated
with check (
  student_id = auth.uid()
  and public.current_user_role() = 'student'
  and school_id = public.current_user_school_id()
);

drop policy if exists career_assessment_results_update_self on public.career_assessment_results;
create policy career_assessment_results_update_self
on public.career_assessment_results
for update
to authenticated
using (student_id = auth.uid())
with check (student_id = auth.uid() and school_id = public.current_user_school_id());
