alter table public.requests
  add column if not exists teacher_id uuid references public.profiles(id) on delete set null;

create table if not exists public.counselor_availability (
  id bigint generated by default as identity primary key,
  counselor_id uuid not null unique references public.profiles(id) on delete cascade,
  school_id text not null,
  weekly_schedule jsonb not null default '{}'::jsonb,
  blocked_slots jsonb not null default '[]'::jsonb,
  meeting_duration integer not null default 30,
  buffer_time integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.counselor_availability
  drop constraint if exists counselor_availability_meeting_duration_check;

alter table public.counselor_availability
  add constraint counselor_availability_meeting_duration_check
  check (meeting_duration in (15, 30, 45, 60));

alter table public.counselor_availability
  drop constraint if exists counselor_availability_buffer_check;

alter table public.counselor_availability
  add constraint counselor_availability_buffer_check
  check (buffer_time in (0, 5, 10, 15));

create index if not exists idx_requests_school_teacher on public.requests (school_id, teacher_id);
create index if not exists idx_counselor_availability_school on public.counselor_availability (school_id, counselor_id);

alter table public.counselor_availability enable row level security;

-- Backfill old teacher referrals that were stored in counselor_id.
update public.requests r
set teacher_id = r.counselor_id,
    counselor_id = null,
    counselor_name = 'Unassigned'
from public.profiles p
where r.teacher_id is null
  and r.counselor_id = p.id
  and p.role = 'teacher';

drop policy if exists requests_insert_scope on public.requests;
create policy requests_insert_scope
on public.requests
for insert
to authenticated
with check (
  school_id = public.current_user_school_id()
  and (
    (
      public.current_user_role() = 'student'
      and student_id = auth.uid()
      and teacher_id is null
    )
    or public.current_user_role() = 'counselor'
    or (
      public.current_user_role() = 'teacher'
      and teacher_id = auth.uid()
      and exists (
        select 1
        from public.profiles s
        where s.id = student_id
          and s.role = 'student'
          and s.school_id = public.current_user_school_id()
      )
      and (
        counselor_id is null
        or exists (
          select 1
          from public.profiles c
          where c.id = counselor_id
            and c.role = 'counselor'
            and c.school_id = public.current_user_school_id()
        )
      )
    )
  )
);

drop policy if exists requests_update_scope on public.requests;
create policy requests_update_scope
on public.requests
for update
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
    or (public.current_user_role() = 'teacher' and teacher_id = auth.uid())
  )
)
with check (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
    or (public.current_user_role() = 'teacher' and teacher_id = auth.uid())
  )
);

drop policy if exists requests_delete_scope on public.requests;
create policy requests_delete_scope
on public.requests
for delete
to authenticated
using (
  school_id = public.current_user_school_id()
  and (
    (public.current_user_role() = 'student' and student_id = auth.uid())
    or public.current_user_role() = 'counselor'
    or (public.current_user_role() = 'teacher' and teacher_id = auth.uid())
  )
);

drop policy if exists counselor_availability_select_school on public.counselor_availability;
create policy counselor_availability_select_school
on public.counselor_availability
for select
to authenticated
using (
  school_id = public.current_user_school_id()
);

drop policy if exists counselor_availability_insert_self on public.counselor_availability;
create policy counselor_availability_insert_self
on public.counselor_availability
for insert
to authenticated
with check (
  public.current_user_role() = 'counselor'
  and counselor_id = auth.uid()
  and school_id = public.current_user_school_id()
);

drop policy if exists counselor_availability_update_self on public.counselor_availability;
create policy counselor_availability_update_self
on public.counselor_availability
for update
to authenticated
using (
  public.current_user_role() = 'counselor'
  and counselor_id = auth.uid()
  and school_id = public.current_user_school_id()
)
with check (
  public.current_user_role() = 'counselor'
  and counselor_id = auth.uid()
  and school_id = public.current_user_school_id()
);

drop policy if exists counselor_availability_delete_self on public.counselor_availability;
create policy counselor_availability_delete_self
on public.counselor_availability
for delete
to authenticated
using (
  public.current_user_role() = 'counselor'
  and counselor_id = auth.uid()
  and school_id = public.current_user_school_id()
);
