-- Recommendation-letter writing workspace: lets a teacher draft the actual
-- letter on-platform (guided sections -> merged document) instead of
-- copying a one-shot AI draft out to Google Docs. Deliberately its own
-- table with teacher-only RLS (no student/counselor/parent policy branches
-- at all) because recommendation letters are conventionally confidential
-- from the applicant -- unlike recommendation_details on `requests`, which
-- the student who submitted it can already see via requests_select_scope.

create table if not exists public.recommendation_letter_documents (
  id bigint generated by default as identity primary key,
  request_id bigint not null unique references public.requests(id) on delete cascade,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  school_id text not null,
  angle text check (angle in ('academic', 'leadership', 'challenge', 'well_rounded')),
  opening text not null default '',
  body1 text not null default '',
  body2 text not null default '',
  closing text not null default '',
  merged_content text not null default '',
  is_merged boolean not null default false,
  status text not null default 'drafting' check (status in ('drafting', 'final')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_recommendation_letter_documents_teacher
  on public.recommendation_letter_documents (school_id, teacher_id);

-- Reuses public.touch_updated_at(), defined in
-- 20260728000000_student_academic_profile.sql.
drop trigger if exists recommendation_letter_documents_updated_at on public.recommendation_letter_documents;
create trigger recommendation_letter_documents_updated_at
  before update on public.recommendation_letter_documents
  for each row execute function public.touch_updated_at();

alter table public.recommendation_letter_documents enable row level security;

drop policy if exists recommendation_letter_documents_teacher_only on public.recommendation_letter_documents;
create policy recommendation_letter_documents_teacher_only
on public.recommendation_letter_documents
for all
to authenticated
using (
  school_id = public.current_user_school_id()
  and public.current_user_role() = 'teacher'
  and teacher_id = auth.uid()
)
with check (
  school_id = public.current_user_school_id()
  and public.current_user_role() = 'teacher'
  and teacher_id = auth.uid()
);
